name: Run Unix Commands
on: [push]

jobs:
  execute-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Create and Navigate Directories
        run: |
          sudo useradd -m -s /bin/bash labuser
          id labuser
          cat /etc/passwd
