name: Run Unix Commands
on: [push]

jobs:
  execute-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run My Unix Commands
        run: |
          echo "=== System Info ==="
          uname -a
          echo "=== Active User ==="
          whoami
