name: Run Unix Commands
on: [push]

jobs:
  execute-bash:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Run Unix commands
        run: |
          echo "Hello from GitHub Actions!"
          pwd
          ls -la
